### ISSUE TITLE
if the output of SSD is used as input to another network

### ISSUE THREAD

**Issue by wyf888fly** [Redhwan-A/6DoFHPE#2]
May I ask if the output of SSD is used as input to another network, and if there are multiple models cascading together.

**Comment by Redhwan-A** [comment]
@wyf888fly, we used two models, one for head detection and one for HPE in real-time video only.

**Comment by wyf888fly** [comment]
> @wyf888fly, we used two models, one for head detection and one for HPE in real-time video only.
first,thank you for your reply.
Is the model used for head detection SSD ?

**Comment by Redhwan-A** [comment]
Yes. We mentioned that in our paper.

**Comment by wyf888fly** [comment]
In an environment with multiple people (such as 30 people), some heads cannot be detected. What problem is causing this? Is there a lot of data in your training set with multiple people? Perhaps this SSD model cannot be well generalized to my data. Do I need to use my own dataset to train the SSD model.

**Comment by Redhwan-A** [comment]
Our model is designed to detect many heads (no limit), such as 30 or 100. Note: there is some limitation when occlusion or people are far. Maybe you need to change the confidence rate. For example, change from 0.8 to 0.3. In this case, it will detect objects that are not real heads.

**Comment by wyf888fly** [comment]
Thank you for your reply
May I ask where I can modify the confidence level from 0.8 to 0.3? It doesn't seem to be in demo3DoF. py

**Comment by wyf888fly** [comment]
> @wyf888fly, we used two models, one for head detection and one for HPE in real-time video only.
Thank you for sharing your great code. 😺
Where is the connection between these two networks (so that I can change the front-end network to YOLO), what is the data being transmitted, and is it an image segmented into small avatars

**Comment by wyf888fly** [comment]
> Our model is designed to detect many heads (no limit), such as 30 or 100. Note: there is some limitation when occlusion or people are far. Maybe you need to change the confidence rate. For example, change from 0.8 to 0.3. In this case, it will detect objects that are not real heads.
Thank you, I have found the confidence level on hdssd.py
